print('***************************************')
print('My Coffee Shop')
print('Number of coffees bought?')
print('3')
print('Number of muffins bought?')
print('3')
print('Number of donuts bought?')
print('2')
print('Number of bagels bought?')
print('1')
print('***************************************')
print('                                       ')
print('                                       ')
print('***************************************')
print('My Coffee and Muffin Shop Receipt')
print('3 Coffee at $5 each: $ 15.00')
print('3 Muffins at $4 each: $ 12.00')
print('2 Donuts at $4 each: $ 12.00')
print('1 Bagel at $3 each: $ 3.00')
print('6% tax: $ 2.52')
print('---------')
print('Total: $ 44.52')
print('***************************************')
print('                                       ')
print('Thank you, we will see you soon!  :)   ')
print('                                       ')
print('***************************************')
