print('***************************************')
print('My Coffee and Muffin Shop')
print('Number of coffees bought?')
print('3')
print('Number of muffins bought?')
print('3')
print('***************************************')
print('                                       ')
print('                                       ')
print('***************************************')
print('My Coffee and Muffin Shop Receipt')
print('3 Coffee at $5 each: $ 15.00')
print('3 Muffins at $4 each: $ 12.00')
print('6% tax: $ 1.62')
print('---------')
print('Total: $ 28.62')
print('***************************************')
